// SPDX-License-Identifier: MIT
/**
 * Perxona Connect Kit -- Presenter API contract
 *
 * AUTO-GENERATED by Perxona Connect Kit codegen. DO NOT EDIT.
 * Generated from the Perxona widget presenter interface.
 *
 * <sv-presenter> implements IPresentationWidget. Use this file for IDE
 * autocomplete and JSDoc when calling presenter methods from your integration.
 *
 * This file also includes the supporting data types and the <sv-presenter>
 * event types (PresentationWidgetEvent and friends) for use with addEventListener.
 */
// -- type/CameraConfig.ts ----------------------------------------------------

export declare enum CameraAngle {
    Fullbody = "fullbody",// Framing.HeadToToe
    Halfbody = "halfbody"
}
export type CameraFOV = {
    distance?: number;
    vertical?: number;
    horizontal: number;
};
export declare enum ScreenFitStrategy {
    FitWidth = "fit-width",
    FitHeight = "fit-height",
    Adaptive = "adaptive"
}

// -- type/CustomEvents.ts ----------------------------------------------------

export declare enum PresentationWidgetEvent {
    PRESENTER_STATUS = "PRESENTER_STATUS",
    ASSET_LOADING_PROGRESS = "ASSET_LOADING_PROGRESS",
    AUDIO_PLAYBACK_STATE = "AUDIO_PLAYBACK_STATE",
    SPEECH_TOKEN_EXPIRED = "SPEECH_TOKEN_EXPIRED",
    CONNECT_TOKEN_EXPIRED = "CONNECT_TOKEN_EXPIRED",
    PERFORMANCE_START = "PERFORMANCE_START",
    PERFORMANCE_END = "PERFORMANCE_END",
    ALL_PERFORMANCE_FINISHED = "ALL_PERFORMANCE_FINISHED",
    PERFORMANCE_STATE = "PERFORMANCE_STATE",
    PLAYING_SPEECH_TEXT = "PLAYING_SPEECH_TEXT"
}
export declare enum PresenterStatus {
    Uninitialized = "Uninitialized",
    Initializing = "Initializing",
    Ready = "Ready"
}
export declare enum AssetType {
    Avatar = "Avatar",
    Motion = "Motion",
    Scene = "Scene"
}
export declare enum PerformanceState {
    Idle = "Idle",
    Listening = "Listening",
    Thinking = "Thinking",
    Talking = "Talking"
}
export interface PresentationEvent {
    eventType: PresentationWidgetEvent;
}
export declare class PresenterStatusEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.PRESENTER_STATUS;
    readonly status: PresenterStatus;
    constructor(status: PresenterStatus);
}
export declare class AssetLoadingProgressEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.ASSET_LOADING_PROGRESS;
    readonly assetType: AssetType;
    readonly progress: number;
    constructor(assetType: AssetType, progress: number);
}
export declare class AudioPlaybackStateEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.AUDIO_PLAYBACK_STATE;
    readonly state: AudioContextState;
    constructor(state: AudioContextState);
}
export declare class SpeechTokenExpiredEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.SPEECH_TOKEN_EXPIRED;
}
/**
 * Dispatched when the Connect Kit Bearer JWT has expired or is about to expire, so the host
 * application can obtain a fresh token and call `refreshConnectToken`.
 *
 * Triggered by `ConnectProvider` whenever a Connect API call responds with 401.
 */
export declare class ConnectTokenExpiredEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.CONNECT_TOKEN_EXPIRED;
}
export declare class PerformanceStartEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.PERFORMANCE_START;
}
export declare class PerformanceEndEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.PERFORMANCE_END;
}
export declare class AllPerformanceFinishedEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.ALL_PERFORMANCE_FINISHED;
}
export declare class PerformanceStateEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.PERFORMANCE_STATE;
    readonly state: PerformanceState;
    constructor(state: PerformanceState);
}
export declare class PlayingSpeechTextEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.PLAYING_SPEECH_TEXT;
    readonly text: string;
    constructor(text: string);
}

// -- type/PresentationError.ts -----------------------------------------------

export declare enum PresentationResultCode {
    OK = "0",
    COMPONENT_UNMOUNTED = "100",
    PRESENTER_NOT_READY = "101",
    AUDIO_CONTEXT_UNAVAILABLE = "200",
    VOICE_NOT_CONFIGURED = "300",
    NOT_INITIALIZED = "301",
    SPEECH_FORMAT_UNSUPPORTED = "302",
    PRESENTATION_INTERRUPTED = "303",
    PRESENTATION_REQUEST_FAILED = "400",
    NOT_IMPLEMENTED = "900"
}
export declare class PresentationResult {
    readonly success: boolean;
    readonly code: PresentationResultCode;
    readonly message?: string | undefined;
    private constructor();
    static ok(): PresentationResult;
    static error(code: PresentationResultCode, message: string): PresentationResult;
    static componentUnmounted(): PresentationResult;
    static presentationInterrupted(): PresentationResult;
    static presenterNotReady(currentStatus: PresenterStatus): PresentationResult;
    static voiceNotConfigured(): PresentationResult;
    static notInitialized(): PresentationResult;
    static speechFormatUnsupported(): PresentationResult;
    static presentationRequestFailed(message: string): PresentationResult;
    static notImplemented(message: string): PresentationResult;
}

// -- type/PresentationTarget.ts ----------------------------------------------

/**
 * Describes what `initialize` should present.
 *
 * Either a bundled `chatbotId` (which resolves to an avatar, scene, and voice together), or an
 * explicit `avatarId` / `sceneId` / `voiceId` combination for finer-grained control. The `type`
 * discriminant lets callers `switch` on it with exhaustive checking, instead of narrowing
 * structurally (e.g. `'chatbotId' in target`).
 *
 * `chatbotId` is strictly all-or-nothing — it intentionally carries no other fields (e.g. no
 * per-call `voiceId` override). Callers who need to customize the voice should use the explicit
 * `avatarId` / `sceneId` / `voiceId` variant instead.
 *
 * TODO(https://github.com/XRSPACE-Inc/perxona/issues/2294): resolving the `chatbot` shape via the
 * Connect API is not implemented yet (the backend endpoint doesn't exist) — see
 * `ConnectProvider.resolveTarget`. The `explicit` shape is fully resolved. Once the chatbot
 * backend API lands, `chatbotId` here should likely be resolved by a `Chatbot` module that wraps
 * `Presenter` (the same way `PerxonaWidget` wraps `Presenter`) rather than folded into
 * `Presenter`'s own resolution flow — see the linked issue for the architecture discussion before
 * implementing this shape.
 */
export type PresentationTarget = {
    type: 'chatbot';
    /** ID of a pre-configured chatbot bundling an avatar, scene, and voice together. */
    chatbotId: string;
} | {
    type: 'explicit';
    /** The ID of the avatar to initialize. */
    avatarId: string;
    /** The ID of the scene to initialize. */
    sceneId: string;
    /** The ID of the voice to use when synthesizing speech for `present`. */
    voiceId?: string;
};

// -- IPresentationWidget.ts --------------------------------------------------

/**
 * Interface for the Presentation Widget.
 *
 * This is the public contract for the `<sv-presenter>` custom element used by Connect Kit
 * integrators.
 *
 * **Performance State Hierarchy:**
 * Avatar animations follow a strict priority hierarchy to handle concurrent state requests:
 * 1. **Custom** (Highest) - Specific motions embedded via `present`.
 * 2. **Talking** - Standard speaking animation active during `present`.
 * 3. **Thinking** - Triggered by `setThinking(true)`.
 * 4. **Listening** - Triggered by `setListening(true)`.
 * 5. **Idle** (Lowest) - The default state when no other states are active.
 *
 * Higher-priority states always visually override lower-priority ones. For instance, if both
 * `setListening(true)` and `setThinking(true)` are called, the avatar will perform Thinking.
 * If `setThinking(false)` is subsequently called, the avatar will fall back to Listening.
 */
export interface IPresentationWidget {
    /**
     * Initializes the presentation widget with the specified target (chatbot, or avatar/scene/voice)
     * and authenticates against the Connect API.
     *
     * The resolved voice is retained internally and used by every subsequent `present` call.
     * `connectToken` authenticates the Connect API calls used to resolve `target`; use
     * `refreshConnectToken` afterwards to rotate it as it expires.
     *
     * @param connectToken The Connect Kit Bearer JWT used to authenticate Connect API calls
     * @param target Either `{ type: 'chatbot', chatbotId }` or
     *   `{ type: 'explicit', avatarId, sceneId, voiceId? }`
     */
    initialize(connectToken: string, target: PresentationTarget): Promise<void>;
    /**
     * Presents content: synthesizes it into speech using the voice provided to `initialize`, and
     * plays it back on the avatar.
     *
     * Note: This activates the top-priority states (**Custom** / **Talking**). Any active lower-priority
     * states (Thinking, Listening) will be visually overridden and hidden until the performance completes
     * or is interrupted.
     *
     * `content` is plain spoken text; it may also embed Perxona motion markup (e.g. `[MOTION
     * id:priority;faceId]` style annotations) to drive specific gestures at specific points in the
     * speech. Any embedded markup is resolved and stripped internally — callers do not need to
     * pre-process or strip it themselves before display. It is sent to the Connect API together
     * with the `avatarId` / `voiceId` resolved by `initialize`, which returns a formatted speech
     * payload and a motion performance manifest that are then synthesized and played back.
     *
     * The returned promise never rejects; it resolves with an error `PresentationResult` if no
     * target has been resolved yet, the resolved target has no voice configured, the component is
     * unmounted, or the Connect API request/response could not be used (e.g. an unsupported speech
     * format). Calling `present` multiple times in quick succession is safe — playback is always in
     * the same order the calls were made.
     *
     * It also resolves with an `AUDIO_CONTEXT_UNAVAILABLE` error until `resumeAudioPlayback` has
     * been called at least once — the SDK never resumes the AudioContext on the caller's behalf; see
     * `resumeAudioPlayback`.
     *
     * @param content The text content to be spoken, optionally containing embedded Perxona motion markup
     * @returns A promise resolving to a PresentationResult indicating the success or failure of the play request, along with error code and message if applicable.
     */
    present(content: string): Promise<PresentationResult>;
    /**
     * Presents caller-provided audio directly, bypassing built-in speech synthesis, and plays it
     * back on the avatar.
     *
     * TODO: wiring this to actual audio playback is not implemented yet.
     *
     * @param audio The raw audio data to play back (e.g. a WAV/PCM buffer from your own TTS or STT pipeline).
     * @param content The text to display, optionally containing embedded Perxona motion markup
     * that is resolved and stripped internally.
     * @returns A promise resolving to a PresentationResult indicating the success or failure of the play request, along with error code and message if applicable.
     */
    presentWithAudio(audio: ArrayBuffer, content: string): Promise<PresentationResult>;
    /**
     * Interrupts the current presentation and clears the presentation queue.
     *
     * Note: This clears the Custom and Talking states, immediately revealing any underlying active
     * states (like Thinking or Listening) or falling back to Idle.
     */
    interruptPresentation(): void;
    /**
     * Set the avatar to be in listening state, which will trigger the corresponding motions.
     *
     * Note: The listening motion will only be visible if no higher-priority states (Custom, Talking, or Thinking) are active.
     *
     * @param isListening A boolean indicating whether the avatar should be in listening state.
     */
    setListening(isListening: boolean): void;
    /**
     * Set the avatar to be in thinking state, which will trigger the corresponding motions.
     *
     * Note: The thinking motion will override the Listening, Idle state, but will remain hidden if a performance
     * (Custom or Talking) is currently playing.
     *
     * @param isThinking A boolean indicating whether the avatar should be in thinking state.
     */
    setThinking(isThinking: boolean): void;
    /**
     * Mute or unmute the audio output of the speech performance.
     *
     * @param muted A boolean indicating whether the audio should be muted.
     */
    muteAudio(muted: boolean): void;
    /**
     * Resumes the AudioContext to comply with browser autoplay policies.
     *
     * Browsers block autoplay audio until the user interacts with the page.
     * Call this method from a direct user interaction callback (e.g., a button click)
     * to ensure speech audio can be played.
     *
     * Must be called at least once before `present` / `presentWithAudio` can succeed \u2014 the SDK
     * never resumes the AudioContext on its own; see `present`'s `AUDIO_CONTEXT_UNAVAILABLE` case.
     *
     * @returns A Promise that resolves when the context has resumed. The promise is rejected if the context has already been closed.
     */
    resumeAudioPlayback(): Promise<void>;
    /**
     * Updates the camera angle of the viewer.
     *
     * @param cameraAngle The desired camera angle, either 'fullbody' or 'halfbody'.
     * This will adjust the view to show either the full body or just the upper half of the avatar.
     */
    updateCameraAngle(cameraAngle: CameraAngle): void;
    /**
     * Adjust the camera's field of view (FOV) settings.
     *
     * @param fov The camera field of view settings, including distance, vertical FOV, and horizontal FOV.
     */
    updateCameraFOV(fov: CameraFOV): void;
    /**
     * Used to refresh the Connect Kit Bearer JWT when it expired or about to expire, to ensure
     * uninterrupted access to the Connect API. See also the `CONNECT_TOKEN_EXPIRED` event.
     *
     * @param token The Connect Kit Bearer JWT.
     */
    refreshConnectToken(token: string): void;
}
